### ISSUE TITLE
rake assets:precompile fails / Execjs throws parsing error

### ISSUE THREAD

**Issue by whatcould** [whatcould/webshims-rails#11]
`rake assets:precompile` fails in Rails in version 1.11.6. Getting this down, will work on a fix later today.

In 1.11.6, this new line: https://github.com/aFarkas/webshim/blob/gh-pages/src/shims/combos/14.js#L930

...originally from es5-shim: https://github.com/kriskowal/es5-shim/blob/master/es5-shim.js#L959

Throws this error:

```
rake aborted!
Invalid syntax: 8e-5.toFixed (line: 3, col: 8394, pos: 8480)

Error
    at new JS_Parse_Error (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:3096:22)
    at js_error (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:3104:15)
    at parse_error (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:3196:17)
    at read_num (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:3229:25)
    at Object.next_token (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:3435:42)
    at Object.custom [as input] (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:6081:46)
    at next (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:3546:37)
    at expr_op (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:4047:25)
    at expr_ops (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:4055:24)
    at maybe_conditional (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:4059:28)
    at maybe_assign (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:4083:28)
    at /private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:4097:28
    at prog1 (/private/var/folders/4x/8v7sksw13yj84fjrmdwh81c80000gn/T/execjs20131211-37580-1w7yiw4.js:4131:23)
```

Appears to have something to do with `(0.00008).toFixed(3) !== '0.000'` ??

**Comment by ideaoforder** [comment]
We're having a related problem. When deploying, we get:
LoadError: cannot load such file -- sass 

We're using LESS, not SASS, but I don't see SASS listed as a dependency. Any ideas?

**Comment by whatcould** [comment]
Seems unrelated to me. You mean, deploying to Heroku? Did you try precompiling assets locally?

**Comment by ideaoforder** [comment]
We're deploying to a Rackspace Cloud server with a pretty typical setup. The file that's raising the error is this one:
https://github.com/whatcould/webshims-rails/blob/master/vendor/assets/javascripts/webshims/shims/jme/_icons.scss

I can see in that same folder there's a controls.css and controls.css.scss file, but the _icons file doesn't have a compiled version, and so during the precompile stage, SASS is trying to compile it but can't. So there probably just needs to be an _icons.css file, would be my guess.
